//! Pure functions mapping Session / ActivityLog / Reflection rows → chunk text
//! ready to embed. No DB or network I/O — input is rows, output is strings.

use chrono::{DateTime, Utc};

/// Subset of the Session table we need to render a per-session chunk.
/// Defined locally so the corpus module doesn't depend on the API types.
#[derive(Debug, Clone)]
pub struct SessionChunkInput {
    pub id: String,
    pub start_time: DateTime<Utc>,
    pub end_time: Option<DateTime<Utc>>,
    pub planned_duration: i32,
    pub actual_duration: Option<i32>,
    pub project_name: Option<String>,
    pub productivity_score: Option<i32>,
    pub top_apps: Vec<(String, i32)>,
}

/// Render one session into the chunk text used by the embedder + LLM.
/// Format anchored by `golden_session_chunk` test — change with care.
pub fn render_session_chunk(s: &SessionChunkInput) -> String {
    let date = s.start_time.format("%a %Y-%m-%d");
    let start = s.start_time.format("%H:%M");
    let end = s
        .end_time
        .map(|e| e.format("%H:%M").to_string())
        .unwrap_or_else(|| "??".to_string());

    let actual = s
        .actual_duration
        .map(|m| m.to_string())
        .unwrap_or_else(|| "?".into());

    let project = s
        .project_name
        .as_deref()
        .map(|n| format!(" Project: {n}."))
        .unwrap_or_default();

    let prod = s
        .productivity_score
        .map(|p| format!(" Productivity {p}/100."))
        .unwrap_or_default();

    let apps = if s.top_apps.is_empty() {
        String::new()
    } else {
        let parts: Vec<String> = s
            .top_apps
            .iter()
            .take(5)
            .map(|(n, m)| format!("{n} {m}m"))
            .collect();
        format!(" Top apps: {}.", parts.join(", "))
    };

    format!(
        "[Session] {date} {start}-{end} ({planned}min planned, {actual}min actual).{project}{prod}{apps}",
        planned = s.planned_duration,
    )
}

/// Aggregated stats for a single calendar day. Generated by a nightly
/// indexer job that rolls Sessions + ActivityLogs into one summary chunk.
#[derive(Debug, Clone)]
pub struct DayChunkInput {
    pub date: chrono::NaiveDate,
    pub session_count: i32,
    pub total_focus_minutes: i32,
    pub best_window: Option<String>,
    pub top_apps: Vec<(String, i32)>,
    pub lowest_productivity_label: Option<String>,
}

pub fn render_day_chunk(d: &DayChunkInput) -> String {
    let date = d.date.format("%a %Y-%m-%d");
    let hours = d.total_focus_minutes as f32 / 60.0;
    let best = d
        .best_window
        .as_deref()
        .map(|w| format!(" Best window {w}."))
        .unwrap_or_default();
    let apps = if d.top_apps.is_empty() {
        String::new()
    } else {
        let parts: Vec<String> = d
            .top_apps
            .iter()
            .take(3)
            .map(|(n, m)| format!("{n} {}h{}m", m / 60, m % 60))
            .collect();
        format!(" Top apps: {}.", parts.join(", "))
    };
    let lowest = d
        .lowest_productivity_label
        .as_deref()
        .map(|l| format!(" Lowest productivity: {l}."))
        .unwrap_or_default();

    format!(
        "[Day] {date}. {sc} sessions, {hours:.1}h focused.{best}{apps}{lowest}",
        sc = d.session_count,
    )
}

#[derive(Debug, Clone)]
pub struct ReflectionChunkInput {
    pub date: chrono::NaiveDate,
    pub questions: Vec<String>,
    pub answer: String,
}

pub fn render_reflection_chunk(r: &ReflectionChunkInput) -> String {
    let date = r.date.format("%a %Y-%m-%d");
    let q = r.questions.first().map(String::as_str).unwrap_or("(no question)");
    format!("[Reflection] {date}. Q: '{q}' A: '{a}'", a = r.answer)
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn sample_input() -> SessionChunkInput {
        SessionChunkInput {
            id: "sid-1".into(),
            start_time: Utc.with_ymd_and_hms(2026, 5, 12, 9, 30, 0).unwrap(),
            end_time: Some(Utc.with_ymd_and_hms(2026, 5, 12, 10, 57, 0).unwrap()),
            planned_duration: 90,
            actual_duration: Some(87),
            project_name: Some("AuthRefactor".into()),
            productivity_score: Some(80),
            top_apps: vec![
                ("VSCode".into(), 65),
                ("Slack".into(), 12),
                ("Chrome".into(), 10),
            ],
        }
    }

    #[test]
    fn golden_session_chunk() {
        let chunk = render_session_chunk(&sample_input());
        let expected = "[Session] Tue 2026-05-12 09:30-10:57 (90min planned, 87min actual). \
                        Project: AuthRefactor. Productivity 80/100. \
                        Top apps: VSCode 65m, Slack 12m, Chrome 10m.";
        assert_eq!(chunk, expected);
    }

    #[test]
    fn chunk_omits_optional_fields_when_missing() {
        let mut s = sample_input();
        s.project_name = None;
        s.productivity_score = None;
        s.top_apps.clear();
        let chunk = render_session_chunk(&s);
        assert!(chunk.contains("[Session]"));
        assert!(!chunk.contains("Project:"));
        assert!(!chunk.contains("Productivity"));
        assert!(!chunk.contains("Top apps:"));
    }

    #[test]
    fn golden_day_chunk() {
        let d = DayChunkInput {
            date: chrono::NaiveDate::from_ymd_opt(2026, 5, 12).unwrap(),
            session_count: 4,
            total_focus_minutes: 216,
            best_window: Some("9-11am".into()),
            top_apps: vec![
                ("VSCode".into(), 120),
                ("Slack".into(), 35),
                ("Chrome".into(), 28),
            ],
            lowest_productivity_label: Some("email triage".into()),
        };
        let chunk = render_day_chunk(&d);
        let expected = "[Day] Tue 2026-05-12. 4 sessions, 3.6h focused. \
                        Best window 9-11am. \
                        Top apps: VSCode 2h0m, Slack 0h35m, Chrome 0h28m. \
                        Lowest productivity: email triage.";
        assert_eq!(chunk, expected);
    }

    #[test]
    fn day_chunk_handles_zero_sessions() {
        let d = DayChunkInput {
            date: chrono::NaiveDate::from_ymd_opt(2026, 5, 12).unwrap(),
            session_count: 0,
            total_focus_minutes: 0,
            best_window: None,
            top_apps: vec![],
            lowest_productivity_label: None,
        };
        let chunk = render_day_chunk(&d);
        assert_eq!(chunk, "[Day] Tue 2026-05-12. 0 sessions, 0.0h focused.");
    }

    #[test]
    fn golden_reflection_chunk() {
        let r = ReflectionChunkInput {
            date: chrono::NaiveDate::from_ymd_opt(2026, 5, 12).unwrap(),
            questions: vec!["You stopped design at 47/60 — anything blocking?".into()],
            answer: "API spec from product is unclear. Need to ping Maya tomorrow.".into(),
        };
        let chunk = render_reflection_chunk(&r);
        let expected = "[Reflection] Tue 2026-05-12. \
                        Q: 'You stopped design at 47/60 — anything blocking?' \
                        A: 'API spec from product is unclear. Need to ping Maya tomorrow.'";
        assert_eq!(chunk, expected);
    }

    #[test]
    fn reflection_chunk_handles_missing_question() {
        let r = ReflectionChunkInput {
            date: chrono::NaiveDate::from_ymd_opt(2026, 5, 12).unwrap(),
            questions: vec![],
            answer: "raw entry".into(),
        };
        let chunk = render_reflection_chunk(&r);
        assert!(chunk.contains("(no question)"));
        assert!(chunk.contains("raw entry"));
    }
}
