[build]
  command = "prisma generate && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = "DEPLOYMENT.md,.env.production.example"
  SECRETS_SCAN_OMIT_KEYS = "NEXTAUTH_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
